name: Publish NPM package

on:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    uses: kobenguyent/actionsmith/.github/workflows/lint-check.yml@main

  publish:
    uses: kobenguyent/actionsmith/.github/workflows/publish-npm.yml@main
